version: '3.9'

services:
  mysql:
    image: mysql:8.3
    ports:
      - 3306:3306
    volumes:
      - ~/docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=user
      - MYSQL_DATABASE=db

